XengShi/materialYouNewTab

- script.js
> chore: update script.js

- README.md
I fixed the typo in the readme.
> Fix Edge typo Readme.md

- index.html
- script.js
> [feat]: added location disable option

- index.html
- script.js
- style.css
Greetings,
I believe I have fully removed all the issues that were present in my last PR. Here are the main changes:
1. Content now adapts better to thinner aspect ratios
2. The shortcut limit has been raised to 50, as shortcuts now wrap and turn into an interactive dock when they don't fit anymore. (Theoretically, no top limit is needed, but at some point the shortcuts take up to much space i.m.o. and hinder the user experience. Let me know if you want me to remove this limit.)
3. Shortcuts now have a placeholder text for their name and url, instead of a blank line.
4. Adaptive icon option now has the same background color as the original shortcuts.
5. No more weird bugs in the shortcut settings - hopefully - with all major browsers on all major platforms. (Tested on Safari (macOS), …
> Bug fixes and new features for shortcuts.

- script.js
- style.css
It's not perfect, but it works
> New Dark Mode

- index.html
- languages.js
Also added (Turkish) on the bracket.
> Added Bengali (Bangla) Language

- index.html
- languages.js
All elements in the menu can be translated, if there is no translation, English is used. Russian is added.
> Added translation of all interface elements from fallback to English, added Russian

- script.js
Proxy disclaimer will now appear when you turn the proxy on, not when you first open the extension
> Moved proxy disclaimer

- README.md
- languages.js
> Untranslated WeatherAPI in Hindi

- languages.js
- script.js
commented out weather related elements when in idle, it should have solve the bug #84 
Also now 'Seems' and 'Earth' is also not translated just like 'Humidity' when in idle (When offline or can't fetch weather)
PS: Fixed all
> Fix Weather Bug and weather translation

- languages.js
> contd. Update languages.js for date formatting in Czech

- index.html
- languages.js
> feat: add new language vietnamese

- style.css
> Slightly changed position of Temperaure Unit

- index.html
Host your own proxy, Learn more, Input options
when clicked on above buttons, now it opens in a new tab
> The button link opens in a new tab

- script.js
> Made entire search-engine div clickable

- style.css
This PR is subject to review and discussion, please check #140 
Existing:
Changed to:
> Changed color of theme color option in the menu 

- style.css
old:
~~new~~: (changed again, see below)
also
change bluish black in time and temperature to dark greyish black for dark theme
to
> Changed Yellow theme to Golden

- LICENSE
- README.md
- background.js
- index.html
- languages.js
- script.js
- style.css
@XengShi @itz-rj-here please check
> GPL-3.0 License

- languages.js
I noticed some less important mistakes in Czech translation, so I fixed them.
> Apply some fixes to the Czech translation

- index.html
- languages.js
Add Uzbek language translation file
> feat: add uzbek language

- languages.js
- style.css
Fixed the length of the buttons if you have a long language, also added a commented code in language.js to change the length of the menu according to the selected language if necessary.
> Fixed the buttons if you have a long language,

- script.js
+ Localised date format for all languages
+ Disabled alert in adaptiveIconToggle
+ Simplified digital clock date code for easier to read and maintain
> Date l10n in some languages

- languages.js
changed for pt, uz, vi
before:
after:
> Changed menu width for some languages

- script.js
- Stop Recognition: Users can now manually stop recognition by clicking the microphone icon again.
- Live Transcription: The search input updates in real-time as the user speaks, instead of waiting for the speech to finish.
> Enabled Stop Recognition & Live Transcription for Voice Search

- style.css
> Reduced gap after 'Reset settings' option

- languages.js
- script.js
localization of Spanish, Korean and Japanese language
>  Russian translation and l10n of date for newly added language

- index.html
- languages.js
- script.js
- style.css
Closes #181 
- Searchbar Text Input area width now dynamically adapt, in all languages, wrt mic and search button 
- Cursor type no longer change to Text on Search Icon
.
Added toggle to hide mic icon
- Set the initial state of the mic icon visibility and checkbox based on supported browser
(Hid the mic icon in the Brave browser too)
- Translated same
> Fixed the search bar text input area and added toggle to hide mic icon

- feedback.html
- index.html
Feedback link update
and form:
dark mode:
> Feedback/Contact Page

- script.js
for Indonesian:
to 
.
and for Bangla, slider was not working because of using wrong variable ~localizedHumidity~, corrected `humidity`
> Fixed Humidity Slider for Bangla and Indonesian

- style.css
Closes #194 
Matches responsiveness with shortcuts and menu button
> Fixed: AI Tools Button Responsiveness and Mouse Pointer Change

- README.md
- index.html
- languages.js
> Transliteration for search engines and some others

- index.html
- script.js
- style.css
Just commented out the related snippets---- deleted
> Removed fold/unfolding for shortcuts in AI Tools  and Collapse AI Tools when clicked outside

- script.js
- style.css
> Changed default scrollbar to a custom one in Language Selector

- style.css
That one comment issue made a big issue 🤣
> Firefox Scrollbar Issue Fixed

- languages.js
- style.css
Also WeatherAPI transliteration corrected
and added Menu width for tr and changed for pt
for tr
to
for pt
changed to
> Better spacing of theme and language for larger menu width

- index.html
- script.js
- style.css
> feat: Added Wallpaper upload option

- languages.js
Made texts in Japanese more natural.
> Improved Japanese texts

- index.html
- script.js
- style.css
Closes #253 
random image wp if clicked on button
daily new random images if wp selected from random
> Added random wallpaper option and warning for Large images

- languages.js
Adjusted some Marathi words and few mistakes.
> Corrected some spelling mistakes in Marathi language.

- script.js
Fixed: No textshadow for usertext, date/greeting, shortcut name when there is no wallpaper
> No Wallpaper, No TextShadow

- languages.js
Added Idn translation for search engine toggle, upload wallpaper, backup, and restore in response to #195
> Minor Patch Idn Lang

- script.js
- style.css
Google apps on hover _Rotation_ effect removed 
It felt irritative when opening Google apps list
Replaced it to click effect (Dark color to darker colour)
**And Changed width of Upload wallpaper button to fixed %**
to
Changed search engine selector ugly color
to
and
> Removed Google apps hover effect

- languages.js
This PR adds Czech translation strings according to https://github.com/XengShi/materialYouNewTab/discussions/195#discussioncomment-11483437.
> l10n: Update Czech translations

- script.js
- I have Solved the issue of Shortcut search switch.
- Which was not opening when the Suggestion Box for search was visible - open. 
https://github.com/user-attachments/assets/727f4070-c83c-4232-90e4-9e69e51d91cb
> Display None The Suggestion box when shortcut search toggled

- languages.js
- style.css
now correctly changes the language for the close button
> Fix #menuCloseButton

- script.js
Resolved some warnings for Unsafe assignment to innerHTML in Weather stuff
and
> Resolved some warnings for Unsafe assignment to innerHTML

- languages.js
Updated the Bangla Language with the comparation of the English Language.
> Bangla Language Update

- languages.js
Improved Italian translation, and translated: dialog boxes (alerts)
- Discussion #195
> Updated Italian

- style.css
> Added hover effect for AI Tools shortcuts

- script.js
Replaced storing the entire CSS in localStorage with saving only the toggle state.
to
> Optimize Adaptive Icon Toggle State Saving

- script.js
Please describe your changes and the purpose of this pull request.
- Issue #<issue_number>
> WeatherAPI api key update

- languages.js
- manifest.json
- script.js
Now search suggestion appears without proxy too.
- None
> Fixed Search Suggestion for Chromium browsers

- languages.js
New ID translation for alert and to-do list
> Added ID translation for alert and to-do list (and fix translation for the word restore)

- languages.js
This pull request brings some new Czech translation strings onto the scene.
- Issue #195
> l10n: Update Czech translation

- README.md
- index.html
- languages.js
- script.js
I added the Azerbaijani language in language.js. I also gave it as an option in index.html, I tested it, there were no problems, it worked normally. I registered myself in the readme.md file.
- Issue #<issue_number>
> add Azerbaijani language

- languages.js
- added missing Portuguese-BR translations
> Update pt-br translations

- index.html
- languages.js
> Bookmark strings translation (for hi and bn)

- manifest(firefox).json
> Search suggestions without proxy

- index.html
- languages.js
- locales/en.js
- script.js
- style.css
- Changed Bookmark Icon
- Added Translatable tooltip
> Changed Bookmark Icon

- locales/fr.js
Updating Bookmarks strings according to the new folders structure
- Issue #<issue_number>
> Updating Bookmarks strings using fr.js in locales folder

- locales/idn.js
New ID translation for bookmarks and invalid backup file message
- Issue #195
> Added ID translation for bookmarks and invalid backup file message

- README.md
- index.html
- languages.js
- locales/sl.js
- script.js
- tools/languagesAnalysis.html
Added Slovenian translations to the project to enhance multilingual support.
- Previous Pull Request #375
- I have implemented all the suggested tips in the latest version of the project.
> Added Slovenian translations

- tools/languagesAnalysis.html
- Changed Color Theme
- Removed Redundant things
- Formatted Document for better Readability
> Feature: Language Page Enhancement

- index.html
- script.js
- Fixed the Grid & List Toggle
> Fixed Toggle

- languages.js
- locales/ru.js
> Update russian translation.

- script.js
For main branch
Also Closes #372
> Fix: saveCheckboxState of bookmarks toggle

- script.js
- tools/languagesAnalysis.html
fix 12 am
Closes #123 
Closes #296
> Fix hour hand rotation at 00:00

- locales/az.js
- locales/bn.js
- locales/cs.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/hi.js
- locales/idn.js
- locales/it.js
- locales/ja.js
- locales/ko.js
- locales/mr.js
- locales/pt.js
- locales/ru.js
- locales/sl.js
- locales/tr.js
- locales/uz.js
- locales/vi.js
- locales/zh.js
Enhanced language support by aligning translation files `az.js`, `bn.js`, `cs.js`, `es.js`, `fr.js`, `hi.js`, `idn.js`, `it.js`, `ko.js`, `mr.js`, `pt.js`, `ru.js`, `sl.js`, `tr.js`, `uz.js`, `vi.js`, `zh.js` with the structure of the English file `en.js`. Added missing translations as comments and removed unnecessary comments for better consistency and readability.
> Languages Enchantmets

- docs/feedback.html
- manifest.json
- script.js
Fixes the issue with firefox 
- Closes #404 
- Closes #418
> Fix blank color in firefox

- style.css
- Fixes the issue without overlapping or underlapping of Search Suggestions
- Closes #406
> Reduced height of Search Dropdown

- LICENSE
- README.md
- docs/feedback.html
- index.html
- languages.js
- manifest(firefox).json
- manifest.json
- script.js
- style.css
also fixed the issue of keyboard shortcuts working on custom text box.. added a condition to exclude them
> Year changed

- docs/feedback.html
- script.js
- style.css
Telegram feedback link changed
fix an issue:
keyboard shortcuts / and > working even on userText
included: responsiveness of search suggestion dropdown
included: weather data retaining time: 2 min if user using their own api key, else 16 minutes
> Update chrome store branch

- index.html
- locales/en.js
- script.js
- style.css
- Added Tint to Shortcut Icons so they blend with the theme more
- Discussion #417
> Added Tint to Shortcut Icons

- script.js
> Search With removal notice (Chrome store)

- .github/pull_request_template.md
- README.md
Updated PR template
fixed below Contributing Guidelines link
**Checklist**
> - [ ] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
> Updated PR template and fixed link

- docs/Get_WeatherAPI_Key.html
- scripts/script.js
fixed catch block: When user denied for GPS permission, then fetch location from ipinfo
Docs:
- Step 6 added
- faq first 2 questions' answer rewritten
- Closes None
- Related to None
> Fix GPS error fallback

- index.html
- preload.js
- script.js
- style.css
Issue:
1. Thumb moving early
2. after page reload, zoom 1x to kx is visible
k is user selected level
> Added back zoom slider

- README.md
- index.html
- locales/np.js
- scripts/languages.js
- scripts/script.js
- tools/languagesAnalysis.html
Added Nepali language translation
> feat: add translation - np (Nepali)

- scripts/script.js
- style.css
- Fixed the shortcut icons and close button having slight white boundaries
- Made the Close button animation smoother
- Issue #142
> White/Black Border Fixes

- index.html
- preload.js
- script.js
- style.css
Reverts XengShi/materialYouNewTab#432
> Revert "Added back zoom slider"

- locales/idn.js
Updating some strings and added new strings for idn translation
> Update IDN Translation

- script.js
- Minor Fix for Firefox Custom Color Themes
> Firefox Custom Color Theme Fix

- scripts/script.js
- style.css
Refactored Color Picker code
N/A
- None
> Refactored Color Picker and Changed Shades for custom color

- scripts/clock.js
Fixed AM/PM display error in specific languages
- None
> Fixed AM/PM Display Error

- manifest(firefox).json
- manifest.json
- scripts/backup-restore.js
Fix restore wallpaper bug
- Related to #444
> Fix restore wallpaper bug

- locales/fr.js
New translations added for hiding the weather map and activating dark mode
Attach screenshots or screen recordings showcasing the changes, if applicable.
- Closes #<issue_number>
- Related to #<issue_number> (optional)
> New translations added for French Language

- locales/cs.js
This pull request brings Czech translation of new strings, updates changed strings and fixes old ones.
> l10n: Update Czech translation strings

- index.html
- scripts/revert-extension-icon.js
- scripts/script.js
- scripts/search-suggestions.js
Seperated Proxy and Search Suggestions
Added `revert-extension-icon.js`
> Seperated Proxy and Search Suggestions from `script.js`

- scripts/shortcuts.js
This pull request addresses a security vulnerability identified by CodeQL in the shortcuts.js file. The vulnerability was related to the use of innerHTML, which could lead to Cross-Site Scripting (XSS) attacks. The changes involve replacing the use of innerHTML with safer DOM manipulation methods such as createElement and textContent. This ensures that the code is more secure and less prone to XSS attacks.
N/A
- https://github.com/XengShi/materialYouNewTab/security/code-scanning/6
> Fixing Security Vulnerability for shortcuts

- index.html
- locales/bn.js
- locales/en.js
- locales/hi.js
- locales/mr.js
- scripts/languages.js
- scripts/save-load-states.js
Translations for latest new strings (hi, bn, mr)
Also included from #541
> Translations for latest new strings (hi, bn, mr)

- README.md
- index.html
- locales/en.js
- locales/ur.js
- manifest(firefox).json
- manifest.json
- scripts/clock.js
- scripts/languages.js
- scripts/weather.js
- style.css
- tools/languagesAnalysis.html
Supersedes #329 
- Incognito support for the extension
- Load other lang font (vi, ur) only if that lang is selected
> New language: Urdu

- locales/zh_TW.js
Update traditional chinese translation
- None
> Update traditional chinese translation

- index.html
- locales/en.js
- scripts/alert-modal.js
- scripts/languages.js
- scripts/search-suggestions.js
- scripts/wallpaper.js
- scripts/weather.js
- style.css
> Changed GPS button to toggle

- locales/fr.js
Update French translations for GPS features and add disclaimer
- Closes #<issue_number> (if this PR fixes an issue)
- Related to #<issue_number> (if applicable)
> New french translations

- locales/idn.js
Usual update to _idn_ translation
> Update IDN Translations

- locales/bn.js
- locales/en.js
- locales/hi.js
- scripts/bookmarks.js
- scripts/search.js
Update Translations: Hindi and Bengali
> Update Translations: Hindi and Bengali

- locales/fr.js
Please provide a clear and concise description of the changes introduced in this PR and their purpose.
If applicable, attach relevant screenshots or screen recordings showcasing the modifications.
- Closes #<issue_number> (if this PR fixes an issue)
- Related to #<issue_number> (if applicable)
> I10n: Update French translations with new search modes and motivational quotes

- index.html
- locales/bn.js
- locales/en.js
- locales/hi.js
- scripts/clock.js
- scripts/languages.js
- style.css
Added back option to hide clock
https://prem-k-r.github.io/materialYouNewTab/
> Added clock hide option

- index.html
- scripts/browser-utils.js
- scripts/script.js
- scripts/weather.js
- style.css
- Disable quote for 500px -
- for 500px to 1200px hideweather chaged visibility to display for shifting
from
to
> Some changes to hide weather and quotes

- locales/cs.js
This pull request brings the translation of new strings related to hiding clock functionality.
> l10n: Update Czech

- index.html
- locales/en.js
- locales/hi.js
- scripts/languages.js
- scripts/weather.js
Option to show Minimun-Maximum temperature instead of Feels like, off by default
> Option to show Minimun-Maximum temperature instead of Feels like

- CHANGELOG.md
- docs/Get_WeatherAPI_Key.html
- index.html
- locales/bn.js
- locales/cs.js
- locales/en.js
- locales/hi.js
- manifest(firefox).json
- manifest.json
- scripts/languages.js
- scripts/search-suggestions.js
- style.css
Update Bengali  translations and docs
Removed Reddit's permission
> Update Bengali  translations

- locales/idn.js
Update _idn_ translations with some adjustment to string placement and translated word for consistency 
> Update IDN Translations (Fixes and Consistency included)

- CHANGELOG.md
- README.md
- index.html
- locales/de.js
- locales/en.js
- scripts/clock.js
- scripts/languages.js
- scripts/weather.js
- tools/languagesAnalysis.html
Added German language
(Machine translated using DeepL and ChatGPT)
> i18n: Add German language

- CHANGELOG.md
- README.md
- index.html
- locales/fa.js
- scripts/ai-tools.js
- scripts/alert-modal.js
- scripts/clock.js
- scripts/languages.js
- scripts/menu-shortcut-page.js
- scripts/search.js
- scripts/weather.js
- style.css
- tools/languagesAnalysis.html
- Improved Slide-in animation when  `Search with`  is clicked
- Added Support for Persian language, credits: [AMIRHOSSEIN](https://t.me/amirhossein_ahmadi_ir)
- RTL layout
Preview: https://prem-k-r.github.io/materialYouNewTab/
> Add Persian

- locales/fa.js
- scripts/languages.js
- style.css
Fixes https://github.com/XengShi/materialYouNewTab/pull/645#issuecomment-2909526818
> Fix feelsLike element Padding for RTL

- CHANGELOG.md
- README.md
- index.html
- locales/ta.js
- scripts/clock.js
- scripts/languages.js
- scripts/weather.js
- style.css
- tools/languagesAnalysis.html
Fixes issues like:
Humidity, GitHub, Temperature, todo hover
Changed Duck(bird) to brand name
> Tamil language specific

- scripts/clock.js
To replicate the issue:
1. have analog clock, 
2. hide clock, 
3. switch to digital clock.
(no refresh in between)
Closes #687
https://github.com/XengShi/materialYouNewTab/pull/659#issuecomment-2924724503
> Fix greetings/date flickering

- locales/idn.js
Another update for _idn_ translation
> Updated IDN Translation

- scripts/clock.js
> Optimize date and greetings rendering 
