script.js
This pull request addresses issue #5.
I found that the original geolocation service ([geolocation-db.com](https://geolocation-db.com/json/)) is no longer active. Therefore, it returns unusable information, resulting in incorrect user location and weather data.
The solution involves replacing the original geolocation service with a new one, namely [ipapi.co](https://ipapi.co/api/).
=> Switched the geolocation API to `ipapi.co`

languages.js
I improved Czech translation a bit. AI generated translations don't have much context (especially here I think you've not provided much of it) and generate unrelated general strings not suited to the situation, where they are used. I also localized some strings to sound more like Czech speaking (of course the meaning stayed the same).
I didn't find translation for "Double tap to edit". Could you add it, please?
=> i18n: Improve Czech translation

index.html, languages.js, script.js
+ Translated newly added options of Digital clock element in menu
- Added an option to input the location manually.
- Customized date displayed formatting in Hindi: Show full name for month and truncated week days.
- Added missing translations of almost all of the interface elements to English and provided corresponding Hindi translations.
- Mapping of week day in hindi. (It was Sun-Sat in English but corresponding in Hindi was Mon-Sun, so was showing wrong day(current week day+1) in Hindi)
=> Creating Fresh PR: Manual Location + Translation

script.js
Ensured that the IP is only fetched from ipinfo.io if savedLocation is null. 
This involves adding a condition to check if savedLocation exists before making the fetch request to ipinfo.io.
so, fetch to ipinfo.io will only happen if the user hasn't provided a location.
=> Added condition before fetching IP from ipinfo.io to avoid the rate-limiting issue

script.js
1. Remove placeholder text when the user starts editing
2. Restore placeholder if the user leaves the div empty after editing
3. weather tweak: Saving IP address in local storage to minimize errors (rare case). When the user hasn’t entered a location, the code first tries to fetch the IP from ipinfo.io. If that fails or is unavailable, it retrieves the previously stored IP address from local storage to ensure smooth functionality without interrupting the weather data retrieval.
=> related to 'Click here to edit' in script.js

index.html, languages.js, script.js, style.css
- Reduced repetitive lookups of DOM elements
- Added try-catch block in ipinfo.io 
- fetching from city instead of IP
- fallback to auto:ip if fetching fails.
- show fetched location in menu
- Repositioned weather icon
- Changed display of ° to °C or °F for temperature
- Fix: Menu close button's transition for longer text translated language(Hindi and Bengali)
- Changed order of AI tools shortcuts in menu
- Added toggle to show/hide UserTextBox 
- Added toggle to show/hide Greeting in digital clock mode
- Changed some English texts and added translations in Hindi and Bengali based on what I felt was appropriate
=> Optimized Weather stuff and More

script.js
`loadActiveStatus("greetingField", greetingField);` was missing
When switching languages, the "greeting" button in settings looked editable even if it was off.
=> Minor bug fix

script.js
Commented out some code related to shortcut favicons. Previously, the code fetched favicons for shortcuts from GOOGLE_FAVICON_API and attempted to retrieve a higher-quality icon (apple-touch-icon) in the background, updating it when found. With this code commented out, it no longer checks for the apple-touch-icon.
Result: Weather data (Humidity, Feels Like, Location) now appears correctly.
Cons: This change does not necessarily reduce the quality of all icons, but some icons may display at a lower quality without the apple-touch-icon check.
Closes #84
=> Temporary Fix: Display Issue of Weather Data when Custom Shortcuts are Used

index.html, script.js, style.css
Working fine on Chrome and Edge
=> Added Voice Typing (Speech-to-text) feature in Searchbar

script.js
Closes #208 
Bug Issue Fix Requested by @prem-k-r 
Information about the fix: https://screenrec.com/share/QFIG9l4W7o
=> Fixed the Proxy Disclaimer Cancel Button Issue

style.css
Fixed this issue where the text was selectable where is not supposed to be selectable in some versions of Chromium browsers like  Brave.
=> fixed all text selectable

index.html, script.js, style.css
- Added DropDown Support With all the supported search engine In the materialYouNewTab.
- The DropDown Supports all the colors which are currently active as it has used the pre written css classes and styles.
- The Feature has short code and i have focused on clean and readable code
- The Dropdown stores the selected search engine in the local storage same as the radio button does.
- It will automatically detect and select the appropriate search engine from local storage when ever the new tab is been created.
> ###  I have Shared A few Screen Shots Of my work below.
> ### Dark theme
> ### Light Theme & Brave New Tab interface
> ### Option For Enabling Or Disabling the shortcut search
=> Adding Feature/search engine selection

script.js
Please describe your changes and the purpose of this pull request.
- I Have tried to solve the senitize issue for swapDropdown function it is resolved
=> Senitize HTML In swapDropdown Method

script.js
This one I'm less sure about, but these work.
Created a separate PR; if needed(probably not), it's easy to revert.
#292
=> Resolved warnings part 2

script.js
Added immutability to constants that going to DOM directly through innerHTML
#302
=> Firefox Warning Fix - 2.5

style.css
From this
to this
This Pull request fixed the overflowing of text in list items when it is very long and without space.
- None
=> Fixed the Todo Item Overflow

languages.js
Please describe your changes and the purpose of this pull request.
- Issue #<195>
=> Adding translation for ToDo List

index.html, preload.js, script.js, style.css
Added a local storage item for last body background and then use that color as the color of loading screen which will result in no flashes no matter which theme you have except for the very 1st time. 
https://github.com/user-attachments/assets/19f116d5-975f-4267-b096-c1e0387fdc1b
- Closes #327 
- Closes #81 
- Closes #112
=> Fixed the Flash Issue during Reload

script.js
When Ctrl+Click opens a new tab, it switches focus to that new tab, now it stay on bookmarks page
=> Open in new tab without switching focus

script.js
Yep bookmarks still dont works, but no more this error when checking without loading as extension like live page(Github), opened in live server, open as url
View changes as `no whitespace` on
=> No error on Live mode for bookmarks

scripts/script.js, style.css
Updated the mic icon visibility logic by toggling its display property instead of using visibility. 
So now, there is more space to write a query when the mic icon is hidden, as it should be.
Before:
After:
- Closes none
- Related to none
=> Fix: Hide Mic Icon Visibility

locales/it.js, style.css
- The Custom Text doesn't goes over Clock no matter what.
- Custom Text is limited to 3 lines, after that it becomes scrollable
1400+
1200+
700+
- Closes #437
=> Fixed User Text Position

scripts/script.js
- Changed the `mix-blend-mode` property from `lighten` to `screen`, enhancing visibility, especially for `red tones` and other darker colors.
- Adjusted the contrast to ensure consistency with the new blend mode. 
Before:
After:
NA
=> Updated Adaptive Icon css for Better Favicon Visibility

scripts/script.js, style.css
- Just Fixed the Shortcuts overflowing
- After changing "New Shortcut" to "New Shortcut link"
- None
=> Fixed Shortcuts Title Overflow

quotes.js
Deleted function for removing trailing `”` if there is no matching opening `“`
Fixed this issue in original API, so not needed anymore
=> Removed unnecessary code from quotes.js

scripts/weather.js
Using 128x128 sized weather image instead of 64x64
- Closes #532
=> Better weather icons

docs/PageNotFound.html
=> Update PageNotFound page

scripts/backup-restore.js, scripts/bookmarks.js, scripts/google-apps.js, scripts/revert-extension-icon.js, scripts/save-load-states.js, scripts/script.js, scripts/search-suggestions.js
Encode bookmark url 
Fix variable declations
- https://github.com/XengShi/materialYouNewTab/security/code-scanning/7
=> Fix security warnings

locales/fr.js
Update French translations for weather widgets, Dialogs boxes...
- Closes #<issue_number>
- Related to #<issue_number> (optional)
=> New french translations

scripts/script.js, style.css
- Fixed radio button delayed animation when hiding search engines.
- Reduced radio toggle size to 16px for more cleaner UI.
https://github.com/user-attachments/assets/23545d20-0dfd-4e0d-a2ae-a1af2610e076
- Closes #<issue_number>
- Related to #<issue_number> (optional)
=> [Fix]Search radio button hide delay

scripts/weather.js
fahrenheitCheckbox state was being read later than the weather data display.
Removed document.addEventListener("DOMContentLoaded", function ()
=> Fix Fahrenheit Display

index.html, scripts/bookmarks.js, scripts/languages.js, style.css
- Edit bookmarks placeholder -> floating label
- Changed Sort by and View as button UI + text always one liner unless hover
- bug fix: In edit bookmark, disabled save button (if no url) stayed disabled until refreshed
to
=> Bookmarks UI enhancement

locales/cs.js
This pull request brings the Czech translation of the newly added string for prompting the user to confirm the shortcuts reset.
- Related to https://github.com/XengShi/materialYouNewTab/discussions/195#discussioncomment-13336494
=> l10n: Update Czech localization

README.md
Preview: https://github.com/prem-k-r/materialYouNewTab/tree/zen-instruction/README.md
SVG web store banners with Chrome's both light and dark version
Added instructions for Zen Browser
---
.
=> Added instructions for Zen Browser to README

scripts/clock.js
Closes #697 
Refactored the analog clock update logic to track cumulative hand rotations and ensure smooth transitions, especially when hands reset (e.g., from 59s to 0s). Introduced a helper function to calculate the shortest rotation path and prevent backward jumps, resulting in a more visually consistent clock animation.
---
To check I used the following:
``` 
let currentTime;
if (window.debugClockTime) {
currentTime = new Date();
currentTime.setHours(
window.debugClockTime.hours,
window.debugClockTime.minutes,
window.debugClockTime.seconds++
);
} else {
currentTime = new Date();
}
```
and 
```
window.debugClockTime = { hours: 12, minutes: 59, seconds: 55 };
```
on the console to change the time
=> Fix analog clock hand rotation
